### ISSUE TITLE
Enhancement request - function to return the list of available RaMP DB versions rather than displaying them

### ISSUE THREAD

**Issue by taraeicher** [ncats/RaMP-DB#134]
My package depends on RaMP-DB, and I would like users to be able to input a version of RaMP-DB to use. My code would then throw an error if that version is not available. However, to implement this, I would need to pull a list of available versions from RaMP-DB. The current code that is available (listAvailableRaMPDbVersions()) lists the versions as text but does not return them. Is it possible to add this functionality?

**Comment by adtisch** [comment]
We have added RaMP::get_remote_db_version_list() to RaMP 3.0. This function returns all db versions available on the GitHub branch indicated by the "branch" parameter (which defaults to "main").
