### ISSUE TITLE
Cannot install RaMP R package on NIH laptop: PCRE compilation error

### ISSUE THREAD

**Issue by taraeicher** [ncats/RaMP-DB#5]
I am running RStudio Version 1.3.959 on an NIH laptop with Windows 10 Enterprise. I have saved the RaMP database file, installed MySQL version 5.7, and set up the RaMP database in MySQL as specified in the instructions. I have also installed the _devtools_ package in R. However, when I try to install the RaMP R package, I get a PCRE compilation error as shown below:

 > library(devtools)
> Loading required package: usethis
> install_github("ncats/RAMP-DB")
> Downloading GitHub repo ncats/RAMP-DB@master
> √  checking for file 'C:\Users\eichertd\AppData\Local\Temp\RtmpemI9FW\remotes297c1e725c1b\ncats-RaMP-DB-1e7a7d2/DESCRIPTION' (365ms)
> --  preparing 'RaMP': (339ms)
> √  checking DESCRIPTION meta-information ... 
>    Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
>      PCRE pattern compilation error
>    	'unrecognized character follows \'
>    	at 'img/.*$'
>    Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
>      invalid regular expression '^\img/.*$'
>    Execution halted
> Error: Failed to install 'RaMP' from GitHub:
>   System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr:
> E> * checking for file 'C:\Users\eichertd\AppData\Local\Temp\RtmpemI9FW\remotes297c1e725c1b\ncats-RaMP-DB-1e7a7d2/DESCRIPTION' ... OK
> E> * preparing 'RaMP':
> E> * checking DESCRIPTION meta-information ... OK
> E> Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
> E>   PCRE pattern compilation error
> E> 	'unrecognized character follows \'
> E> 	at 'img/.*$'
> E> Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
> E>   invalid regular expression '^\img/.*$'
> E> Execution halted

**Comment by johnbraisted** [comment]
I'll try to resolve this issue today. BTW, I don't seem to be able to assign this case to myself. I'll check with ITRB to see if it's a change to my role in the repository.

**Comment by taraeicher** [comment]
Thanks @johnbraisted! I'm not able to assign it to you either. For some reason, you're not on the list.

**Comment by johnbraisted** [comment]
RaMP-DB has a .Rbuildignore file that contains this regular expression: '^\img/.*$'.  I think it doesn't like '\i' when grepl is called.

This file in the ncats repository is the same as in the mathelab repository. I have a new RTools 4.0.0. Can this be modified in some way? Is the '\' required to skip the one image file we have?  I'll branch and give it a shot.

**Comment by johnbraisted** [comment]
The regular expression was used to ignore image files.  '^\img/.*$' appears to have been intended to skip a directory starting with \img. There is no directory with that name, but one file img1.png that can be ignored by changing the regex to  '^img/.*$'.  Installation has been tested in deploy-conf branch.

**Comment by johnbraisted** [comment]
Tested off master. Windows 10. Rstudio v1.2.5019, R version 4.0.0, Rtools 4.0.0.
