### ISSUE TITLE
Calculate Effect Size from Chemical Class Enrichment

### ISSUE THREAD

**Issue by jnstyles5** [ncats/RaMP-DB#68]
This is not necessarily an issue, but how would someone calculate effect size from chemical class enrichment results?  I've looked at a few methods for fisher exact test such as Cramer's V or odds ratio, but it's not clear to me how to apply the output from chemical class enrichment to these methods.  Perhaps you have a better suggestion for calculating an effect size?

Thank you for your help!

**Comment by Mathelab** [comment]
Hello,
Would returning the odds ratio from the Fisher's test be helpful?
Best,
Ewy

**Comment by Mathelab** [comment]
Closing this issue.  The odds ratio will be returned for the upcoming 3.0 release.
